<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <!-- TargetFrameworks>net10.0-android;net10.0-ios;net10.0-windows10.0.26100;net10.0-browserwasm;net10.0-desktop</TargetFrameworks -->
    <TargetFrameworks>net10.0-windows10.0.26100</TargetFrameworks>
    <Platforms>x64;AnyCPU</Platforms>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>dotNetFractal</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.dotnetfractal</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>dotNetFractal</ApplicationPublisher>
    <!-- Package Description -->
    <Description>dotNetFractal powered by Uno Platform.</Description>
    <!--
      If you encounter this error message:

        error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll.
        Please update to a newer .NET SDK in order to reference this assembly.

      This means that the two packages below must be aligned with the "build" version number of
      the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
      must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
    -->
    <!-- <WindowsSdkPackageVersion>10.0.22621.28</WindowsSdkPackageVersion> -->

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      MVUX;
      SkiaRenderer;
    </UnoFeatures>
    <RootNamespace>dotNetFractal.Uno</RootNamespace>
    <AssemblyName>dotNetFractal.Uno</AssemblyName>
    <Company>Roland Boon</Company>
    <Copyright>Copyright © 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotNetFractal.Logic\dotNetFractal.Logic.csproj" />
    <ProjectReference Include="..\dotNetFractal.UI\dotNetFractal.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\PropertiesPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\FractalAreaEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\ImageResolutionEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\ColorMapEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\FractalSettingsEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\DisplaySettingsEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
